version: 2.1
jobs:
  build:
    working_directory: ~/node-api-framework
    machine:
      image: ubuntu-1604:201903-01

    steps:
      # Checkout to project directory
      - checkout

      # Run commands
      - run:
          name: Run apt-get install
          command: 'sudo apt-get update'
      - run:
          name: Install node@latest
          command: 'sudo apt-get install nodejs'
      - run:
          name: Install npm@latest
          command: 'sudo apt-get install npm'
      - run:
          name: Install dependencies
          command: 'npm install'
      - run:
          name: Run test files
          command: 'npm test'

      # Report test status
      - run:
          name: Uploading coverage to codecov
          command: bash <(curl -s https://codecov.io/bash) -t c84090c8-fb23-4a32-ae23-9cf5692cc8f5
          
      - store_artifacts:
          path: coverage

      - store_test_results:
          path: coverage
