version: 2.1
jobs:
  build:
    working_directory: ~/node-api-framework
    docker:
      - image: circleci/node:10.0.0 # for the CircleCI "Convenience" image
      - image: node:10.0.0 # for the Docker Library image

    steps:
      # Checkout to project directory
      - checkout

      # Run commands
      - run:
          name: Install dependencies
          command: node -v && npm install
      - run:
          name: Run test files
          command: 'npm test'

      # Report test status
      - run:
          name: Uploading coverage to codecov
          command: bash <(curl -s https://codecov.io/bash) -t c84090c8-fb23-4a32-ae23-9cf5692cc8f5
          
      - store_artifacts:
          path: coverage

      - store_test_results:
          path: coverage
